// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shbk2.proto
// Protobuf C++ Version: 5.26.1

#include "shbk2.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace shbk2 {

inline constexpr PhoneRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{0},
        identifier_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PhoneRes::PhoneRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PhoneResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PhoneResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PhoneResDefaultTypeInternal() {}
  union {
    PhoneRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PhoneResDefaultTypeInternal _PhoneRes_default_instance_;

inline constexpr PhoneReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        phone_number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PhoneReq::PhoneReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PhoneReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PhoneReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PhoneReqDefaultTypeInternal() {}
  union {
    PhoneReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PhoneReqDefaultTypeInternal _PhoneReq_default_instance_;

inline constexpr LoginRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoginRes::LoginRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LoginResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginResDefaultTypeInternal() {}
  union {
    LoginRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginResDefaultTypeInternal _LoginRes_default_instance_;

inline constexpr LoginReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        phone_number_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        identifier_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoginReq::LoginReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LoginReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoginReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoginReqDefaultTypeInternal() {}
  union {
    LoginReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoginReqDefaultTypeInternal _LoginReq_default_instance_;
}  // namespace shbk2
static ::_pb::Metadata file_level_metadata_shbk2_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_shbk2_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_shbk2_2eproto = nullptr;
const ::uint32_t
    TableStruct_shbk2_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneReq, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneReq, _impl_.phone_number_),
        0,
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneRes, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneRes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneRes, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneRes, _impl_.desc_),
        PROTOBUF_FIELD_OFFSET(::shbk2::PhoneRes, _impl_.identifier_),
        1,
        0,
        2,
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginReq, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginReq, _impl_.phone_number_),
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginReq, _impl_.identifier_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginRes, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginRes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginRes, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::shbk2::LoginRes, _impl_.desc_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::shbk2::PhoneReq)},
        {10, 21, -1, sizeof(::shbk2::PhoneRes)},
        {24, 34, -1, sizeof(::shbk2::LoginReq)},
        {36, 46, -1, sizeof(::shbk2::LoginRes)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::shbk2::_PhoneReq_default_instance_._instance,
    &::shbk2::_PhoneRes_default_instance_._instance,
    &::shbk2::_LoginReq_default_instance_._instance,
    &::shbk2::_LoginRes_default_instance_._instance,
};
const char descriptor_table_protodef_shbk2_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013shbk2.proto\022\005shbk2\" \n\010PhoneReq\022\024\n\014phon"
    "e_number\030\001 \002(\t\":\n\010PhoneRes\022\014\n\004code\030\001 \002(\005"
    "\022\014\n\004desc\030\002 \001(\t\022\022\n\nidentifier\030\003 \002(\005\"4\n\010Lo"
    "ginReq\022\024\n\014phone_number\030\001 \002(\t\022\022\n\nidentifi"
    "er\030\002 \002(\005\"&\n\010LoginRes\022\014\n\004code\030\001 \002(\005\022\014\n\004de"
    "sc\030\002 \001(\t"
};
static ::absl::once_flag descriptor_table_shbk2_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_shbk2_2eproto = {
    false,
    false,
    208,
    descriptor_table_protodef_shbk2_2eproto,
    "shbk2.proto",
    &descriptor_table_shbk2_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_shbk2_2eproto::offsets,
    file_level_metadata_shbk2_2eproto,
    file_level_enum_descriptors_shbk2_2eproto,
    file_level_service_descriptors_shbk2_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_shbk2_2eproto_getter() {
  return &descriptor_table_shbk2_2eproto;
}
namespace shbk2 {
// ===================================================================

class PhoneReq::_Internal {
 public:
  using HasBits = decltype(std::declval<PhoneReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(PhoneReq, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

PhoneReq::PhoneReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:shbk2.PhoneReq)
}
inline PROTOBUF_NDEBUG_INLINE PhoneReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        phone_number_(arena, from.phone_number_) {}

PhoneReq::PhoneReq(
    ::google::protobuf::Arena* arena,
    const PhoneReq& from)
    : ::google::protobuf::Message(arena) {
  PhoneReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:shbk2.PhoneReq)
}
inline PROTOBUF_NDEBUG_INLINE PhoneReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        phone_number_(arena) {}

inline void PhoneReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PhoneReq::~PhoneReq() {
  // @@protoc_insertion_point(destructor:shbk2.PhoneReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PhoneReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.phone_number_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PhoneReq::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(PhoneReq, _impl_._cached_size_),
              false,
          },
          &PhoneReq::MergeImpl,
          &PhoneReq::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void PhoneReq::Clear() {
// @@protoc_insertion_point(message_clear_start:shbk2.PhoneReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.phone_number_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PhoneReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 35, 2> PhoneReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PhoneReq, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PhoneReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::shbk2::PhoneReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required string phone_number = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PhoneReq, _impl_.phone_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string phone_number = 1;
    {PROTOBUF_FIELD_OFFSET(PhoneReq, _impl_.phone_number_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\14\0\0\0\0\0\0"
    "shbk2.PhoneReq"
    "phone_number"
  }},
};

::uint8_t* PhoneReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shbk2.PhoneReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string phone_number = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_phone_number();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "shbk2.PhoneReq.phone_number");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shbk2.PhoneReq)
  return target;
}

::size_t PhoneReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shbk2.PhoneReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // required string phone_number = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_phone_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PhoneReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PhoneReq*>(&to_msg);
  auto& from = static_cast<const PhoneReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:shbk2.PhoneReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_internal_set_phone_number(from._internal_phone_number());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PhoneReq::CopyFrom(const PhoneReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shbk2.PhoneReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PhoneReq::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

void PhoneReq::InternalSwap(PhoneReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.phone_number_, &other->_impl_.phone_number_, arena);
}

::google::protobuf::Metadata PhoneReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_shbk2_2eproto_getter,
                                   &descriptor_table_shbk2_2eproto_once,
                                   file_level_metadata_shbk2_2eproto[0]);
}
// ===================================================================

class PhoneRes::_Internal {
 public:
  using HasBits = decltype(std::declval<PhoneRes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000006) ^ 0x00000006) != 0;
  }
};

PhoneRes::PhoneRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:shbk2.PhoneRes)
}
inline PROTOBUF_NDEBUG_INLINE PhoneRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        desc_(arena, from.desc_) {}

PhoneRes::PhoneRes(
    ::google::protobuf::Arena* arena,
    const PhoneRes& from)
    : ::google::protobuf::Message(arena) {
  PhoneRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, code_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, code_),
           offsetof(Impl_, identifier_) -
               offsetof(Impl_, code_) +
               sizeof(Impl_::identifier_));

  // @@protoc_insertion_point(copy_constructor:shbk2.PhoneRes)
}
inline PROTOBUF_NDEBUG_INLINE PhoneRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        desc_(arena) {}

inline void PhoneRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, code_),
           0,
           offsetof(Impl_, identifier_) -
               offsetof(Impl_, code_) +
               sizeof(Impl_::identifier_));
}
PhoneRes::~PhoneRes() {
  // @@protoc_insertion_point(destructor:shbk2.PhoneRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PhoneRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.desc_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PhoneRes::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_._cached_size_),
              false,
          },
          &PhoneRes::MergeImpl,
          &PhoneRes::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void PhoneRes::Clear() {
// @@protoc_insertion_point(message_clear_start:shbk2.PhoneRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.desc_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.code_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.identifier_) -
        reinterpret_cast<char*>(&_impl_.code_)) + sizeof(_impl_.identifier_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PhoneRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 27, 2> PhoneRes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PhoneRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::shbk2::PhoneRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PhoneRes, _impl_.code_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.code_)}},
    // optional string desc = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.desc_)}},
    // required int32 identifier = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PhoneRes, _impl_.identifier_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.identifier_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.code_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string desc = 2;
    {PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.desc_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required int32 identifier = 3;
    {PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.identifier_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\16\0\4\0\0\0\0\0"
    "shbk2.PhoneRes"
    "desc"
  }},
};

::uint8_t* PhoneRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shbk2.PhoneRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 code = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_code(), target);
  }

  // optional string desc = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_desc();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "shbk2.PhoneRes.desc");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required int32 identifier = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_identifier(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shbk2.PhoneRes)
  return target;
}

::size_t PhoneRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shbk2.PhoneRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string desc = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_desc());
  }

  if (cached_has_bits & 0x00000006u) {
    // required int32 code = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_code());
    }

    // required int32 identifier = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_identifier());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PhoneRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PhoneRes*>(&to_msg);
  auto& from = static_cast<const PhoneRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:shbk2.PhoneRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_desc(from._internal_desc());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.code_ = from._impl_.code_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.identifier_ = from._impl_.identifier_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PhoneRes::CopyFrom(const PhoneRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shbk2.PhoneRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PhoneRes::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

void PhoneRes::InternalSwap(PhoneRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_, &other->_impl_.desc_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.identifier_)
      + sizeof(PhoneRes::_impl_.identifier_)
      - PROTOBUF_FIELD_OFFSET(PhoneRes, _impl_.code_)>(
          reinterpret_cast<char*>(&_impl_.code_),
          reinterpret_cast<char*>(&other->_impl_.code_));
}

::google::protobuf::Metadata PhoneRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_shbk2_2eproto_getter,
                                   &descriptor_table_shbk2_2eproto_once,
                                   file_level_metadata_shbk2_2eproto[1]);
}
// ===================================================================

class LoginReq::_Internal {
 public:
  using HasBits = decltype(std::declval<LoginReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(LoginReq, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

LoginReq::LoginReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:shbk2.LoginReq)
}
inline PROTOBUF_NDEBUG_INLINE LoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        phone_number_(arena, from.phone_number_) {}

LoginReq::LoginReq(
    ::google::protobuf::Arena* arena,
    const LoginReq& from)
    : ::google::protobuf::Message(arena) {
  LoginReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.identifier_ = from._impl_.identifier_;

  // @@protoc_insertion_point(copy_constructor:shbk2.LoginReq)
}
inline PROTOBUF_NDEBUG_INLINE LoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        phone_number_(arena) {}

inline void LoginReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.identifier_ = {};
}
LoginReq::~LoginReq() {
  // @@protoc_insertion_point(destructor:shbk2.LoginReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoginReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.phone_number_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
LoginReq::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(LoginReq, _impl_._cached_size_),
              false,
          },
          &LoginReq::MergeImpl,
          &LoginReq::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void LoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:shbk2.LoginReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.phone_number_.ClearNonDefaultToEmpty();
  }
  _impl_.identifier_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LoginReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 35, 2> LoginReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LoginReq, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LoginReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::shbk2::LoginReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required int32 identifier = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoginReq, _impl_.identifier_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.identifier_)}},
    // required string phone_number = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.phone_number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string phone_number = 1;
    {PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.phone_number_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required int32 identifier = 2;
    {PROTOBUF_FIELD_OFFSET(LoginReq, _impl_.identifier_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\16\14\0\0\0\0\0\0"
    "shbk2.LoginReq"
    "phone_number"
  }},
};

::uint8_t* LoginReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shbk2.LoginReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string phone_number = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_phone_number();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "shbk2.LoginReq.phone_number");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required int32 identifier = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_identifier(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shbk2.LoginReq)
  return target;
}

::size_t LoginReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shbk2.LoginReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // required string phone_number = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_phone_number());
    }

    // required int32 identifier = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_identifier());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void LoginReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LoginReq*>(&to_msg);
  auto& from = static_cast<const LoginReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:shbk2.LoginReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_phone_number(from._internal_phone_number());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.identifier_ = from._impl_.identifier_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoginReq::CopyFrom(const LoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shbk2.LoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LoginReq::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

void LoginReq::InternalSwap(LoginReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.phone_number_, &other->_impl_.phone_number_, arena);
        swap(_impl_.identifier_, other->_impl_.identifier_);
}

::google::protobuf::Metadata LoginReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_shbk2_2eproto_getter,
                                   &descriptor_table_shbk2_2eproto_once,
                                   file_level_metadata_shbk2_2eproto[2]);
}
// ===================================================================

class LoginRes::_Internal {
 public:
  using HasBits = decltype(std::declval<LoginRes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(LoginRes, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

LoginRes::LoginRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:shbk2.LoginRes)
}
inline PROTOBUF_NDEBUG_INLINE LoginRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        desc_(arena, from.desc_) {}

LoginRes::LoginRes(
    ::google::protobuf::Arena* arena,
    const LoginRes& from)
    : ::google::protobuf::Message(arena) {
  LoginRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:shbk2.LoginRes)
}
inline PROTOBUF_NDEBUG_INLINE LoginRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        desc_(arena) {}

inline void LoginRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
LoginRes::~LoginRes() {
  // @@protoc_insertion_point(destructor:shbk2.LoginRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LoginRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.desc_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
LoginRes::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(LoginRes, _impl_._cached_size_),
              false,
          },
          &LoginRes::MergeImpl,
          &LoginRes::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void LoginRes::Clear() {
// @@protoc_insertion_point(message_clear_start:shbk2.LoginRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.desc_.ClearNonDefaultToEmpty();
  }
  _impl_.code_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LoginRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 27, 2> LoginRes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LoginRes, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LoginRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::shbk2::LoginRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string desc = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(LoginRes, _impl_.desc_)}},
    // required int32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LoginRes, _impl_.code_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(LoginRes, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 code = 1;
    {PROTOBUF_FIELD_OFFSET(LoginRes, _impl_.code_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string desc = 2;
    {PROTOBUF_FIELD_OFFSET(LoginRes, _impl_.desc_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\4\0\0\0\0\0"
    "shbk2.LoginRes"
    "desc"
  }},
};

::uint8_t* LoginRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shbk2.LoginRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 code = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_code(), target);
  }

  // optional string desc = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_desc();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "shbk2.LoginRes.desc");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shbk2.LoginRes)
  return target;
}

::size_t LoginRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shbk2.LoginRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string desc = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_desc());
  }

  // required int32 code = 1;
  if (cached_has_bits & 0x00000002u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void LoginRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LoginRes*>(&to_msg);
  auto& from = static_cast<const LoginRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:shbk2.LoginRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_desc(from._internal_desc());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.code_ = from._impl_.code_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoginRes::CopyFrom(const LoginRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shbk2.LoginRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LoginRes::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

void LoginRes::InternalSwap(LoginRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_, &other->_impl_.desc_, arena);
        swap(_impl_.code_, other->_impl_.code_);
}

::google::protobuf::Metadata LoginRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_shbk2_2eproto_getter,
                                   &descriptor_table_shbk2_2eproto_once,
                                   file_level_metadata_shbk2_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace shbk2
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_shbk2_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
